[project]
name = "class8"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deep-translator>=1.11.4",
    "dotenv>=0.9.9",
    "openai-agents>=0.2.6",
    "rich>=14.1.0",
]
